### PR TITLE
Jelly fixes

### PR DESCRIPTION
**Pull request by artemnovichkov**
- Remove key types
- Refactor category for rounder corners
- Update complete transition logic

### CODE REVIEW

**Comment by SebastianBoldt** [comment]
17 days ago? I am not sure why I missed this PR. I will go through it all at the Weekend. Thanks in advance for contributing to Jelly.

**Comment by artemnovichkov** [comment]
@SebastianBoldt why you didn't merge my PR?

**Comment by SebastianBoldt** [comment]
@artemnovichkov I wasn't sure about all the type inference changes. It is said to have a big impact on compile times and I really don't want that my library slows down the compiling process of other developers. But I think that the adaptions you made are okay. So could you please resolve the conflicts? I will merge it then. Best regards.

**Comment by SebastianBoldt** [comment]
@artemnovichkov Your commit messages are a bit exaggerated. "Update complete transition logic" 😄  .. come on? What you did is that you changed the parameters according to the documentation. It has nothing to do with a complete "Refactoring". Please be a little bit more honest with your next PR.

**Comment by SebastianBoldt** [comment]
@artemnovichkov resolved it by myself 😄 . Thanks for contributing to Jelly.

**Pull request merged**
