### PR TITLE
Flashing UIBlurEffect

### PR DESCRIPTION
**Pull request by glisom**

### CODE REVIEW

**Comment by glisom** [comment]
Essentially what I found was that if you set the defaulted effect or value when the progress of the transition is zero, it prevents the previous animation from creating the flash.

**Comment by SebastianBoldt** [comment]
@glisom I will take a look at it this weekend ;)

**Comment by glisom** [comment]
Hey @SebastianBoldt hope you had a great holiday, have you had a chance to look into this yet?

**Comment by SebastianBoldt** [comment]
Hi @glisom sorry for answering this late. I tested it and it works like a charm. Thank you very much I will merge the PR and create a patch release directly after I merged it.

**Pull request merged**
